### ISSUE TITLE
Manually publish chirp workflow to Dockstore using Github app registration method

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/sounder-sips-chirp-workflows#4]
Modify sounder-sips-chirp-workflows to add a .dockstore.yml file that specifies which CWL files are pulled into Dockstore.
See https://github.com/nlahaye/sounder-sips-application/blob/main/.dockstore.yml for an example.

Then utilize the web interface of Dockstore to register using the Github app method.

**Comment by mliukis** [comment]
@mcduffie I can register the workflow from the Github repo that I own. So that would require me forking their repo - it is what we want?

**Comment by mcduffie** [comment]
Instead of using the Github to register the app we use the full automated, but manually triggered, process.
