### ISSUE TITLE
Exercise building chirp application through automated unity-app-generator process

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/sounder-sips-chirp-workflows#6]

**Comment by mike-gangl** [comment]
was able to manually build the process. note: building on my mac (m1 processor) would not allow the docker container to run in the SPS. I looked for a workaround in repo2docker that would use dockerx to be machine agnostic but couldn't find it.

you can see, after a build, the 'architecture' is not an x86 (amd/intel), which caused conflicts on the executions.

I was able to use my old macbook to build this, so getting the automated system working will really be nice.

**Comment by mcduffie** [comment]
Populated into Dockstore and Dockerhub through automated process with manual push into Gitlab.
